# Implementing PCA by numpy

In [1]:
import numpy as np

In [15]:
x=np.random.randint(10,50,100).reshape(20,5)

In [16]:
print(x)

[[35 29 18 14 33]
 [23 30 10 19 42]
 [15 39 12 15 44]
 [22 20 22 34 31]
 [11 15 28 39 34]
 [15 42 37 23 34]
 [17 29 48 47 33]
 [34 12 37 46 46]
 [36 14 47 49 45]
 [20 37 44 40 15]
 [20 17 34 15 46]
 [31 28 37 36 28]
 [21 43 16 25 35]
 [10 11 26 24 30]
 [11 29 35 16 37]
 [33 11 18 38 49]
 [41 27 31 13 29]
 [31 31 18 21 18]
 [37 39 21 48 21]
 [46 16 45 18 27]]


In [18]:
x_meaned=x-np.mean(x,axis=0)
print(x_meaned.shape)

(20, 5)


cov means covarience matrix. false=column means no.of.col in cov is equal to no,ofcol in origonal data 


In [21]:
cov_mat=np.cov(x_meaned,rowvar=False)
print(cov_mat.shape)

(5, 5)


In [34]:
eigenvalue , eigenvector=np.linalg.eigh(cov_mat)
print(eigenvalue)
print(eigenvector)

[ 46.30969492  96.33681757 118.17662881 139.14604137 234.32818575]
[[-2.41772158e-01 -2.35539152e-01  9.17397256e-01 -5.59593277e-02
  -2.03269180e-01]
 [-6.09977328e-01 -1.17641738e-01 -6.94929871e-02  6.94059706e-01
   3.57127331e-01]
 [-2.60009737e-01  7.33289742e-01  2.48910152e-04  2.01912942e-01
  -5.94905197e-01]
 [-1.65677460e-02 -6.22616370e-01 -3.04789742e-01  2.04844365e-01
  -6.90808486e-01]
 [-7.08233245e-01 -7.29159803e-02 -2.46284693e-01 -6.57586214e-01
  -3.62657807e-03]]


In [40]:
sorted_index=np.argsort(eigenvalue)[::-1]
sorted_eigen_value=eigenvalue[sorted_index]
sorted_eigen_vector=eigenvector[:,sorted_index]

In [41]:
sorted_eigen_value

array([234.32818575, 139.14604137, 118.17662881,  96.33681757,
        46.30969492])

In [42]:
sorted_eigen_vector

array([[-2.03269180e-01, -5.59593277e-02,  9.17397256e-01,
        -2.35539152e-01, -2.41772158e-01],
       [ 3.57127331e-01,  6.94059706e-01, -6.94929871e-02,
        -1.17641738e-01, -6.09977328e-01],
       [-5.94905197e-01,  2.01912942e-01,  2.48910152e-04,
         7.33289742e-01, -2.60009737e-01],
       [-6.90808486e-01,  2.04844365e-01, -3.04789742e-01,
        -6.22616370e-01, -1.65677460e-02],
       [-3.62657807e-03, -6.57586214e-01, -2.46284693e-01,
        -7.29159803e-02, -7.08233245e-01]])

In [43]:
n_components=2 

In [46]:
eigenvector_subset=sorted_eigen_vector[:,0:n_components]

In [48]:
x_reduced=np.dot(eigenvector_subset.transpose(),x_meaned.transpose()).transpose()

In [49]:
x_reduced.shape

(20, 2)

we reduced (20,5) matrix in 20 X 2  by PCA